volumes:
  langflow-postgres:
  langflow-data:

services:
  langflow:
    image: aunymoons/langflow:local # or another version tag on https://hub.docker.com/r/langflowai/langflow 
    #build:
    #  context: /
    #  dockerfile: docker/build_and_push.Dockerfile
    ports:
      - "8080:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
    volumes:
      - langflow-data:/app/langflow
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    expose:
      - 5432
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
